services:
  front:
    build: 
      context: ./Front
      dockerfile: Dockerfile
    ports: 
      - "4000:3000"
    depends_on:
      - backend
    environment: 
      - API_URL=http://backend:8080
      - API_IMAGE_URL=http://api-server:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quizznet.rule=Host(`quizznet.ddns.net`)"
      - "traefik.http.routers.quizznet.entrypoints=websecure"
      - "traefik.http.routers.quizznet.tls.certResolver=letsencrypt"
      - "traefik.http.services.quizznet.loadbalancer.server.port=4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dokploy-network

  backend:
    build: 
      context: ./Backend/QuizzNetBackend/QuizzNetBackend
      dockerfile: Dockerfile
    ports: 
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ConnectionStrings__PostgresConnectionString=Host=postgres;Port=5432;Username=quizznet;Password=quizznet;Database=quizznet
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quizznet.rule=Host(`quizznet.ddns.net`)"
      - "traefik.http.routers.quizznet.entrypoints=websecure"
      - "traefik.http.routers.quizznet.tls.certResolver=letsencrypt"
      - "traefik.http.services.quizznet.loadbalancer.server.port=8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dokploy-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quizznet
      - POSTGRES_PASSWORD=quizznet
      - POSTGRES_DB=quizznet
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DbInit/init.sql:/docker-entrypoint-initdb.d/01_init.sql
    networks:
      - dokploy-network

  pict-rs:
    image: asonix/pictrs:0.5
    restart: unless-stopped
    environment:
      - PICTRS__SERVER__ADDRESS=0.0.0.0:8080
      - PICTRS__MEDIA__VIDEO_ENABLED=false   # отключаем видео
      - PICTRS__MEDIA__ANIMATED_ENABLED=false
    volumes:
      - ./pictrs-data:/mnt
    ports:
      - "8080:8080"  
    networks:
      - dokploy-network       
  
  api-server:
    build: ./API-Images
    restart: unless-stopped
    ports:
      - "3001:3001"  
    environment:
      - PICTRS_URL=http://pict-rs:8080
    depends_on:
      - pict-rs     
    networks:
      - dokploy-network          

volumes:
  postgres_data:

networks:
  dokploy-network:
    external: true
  