CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';

CREATE TABLE public.game (
    id bigint NOT NULL,
    quizz_id bigint NOT NULL,
    leader_user_id bigint NOT NULL,
    link_key uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    create_at timestamp without time zone DEFAULT now() NOT NULL,
    quizz_state text DEFAULT 'Registry'::text NOT NULL,
    questions_id bigint[] DEFAULT '{}'::bigint[] NOT NULL
);


ALTER TABLE public.game OWNER TO quizznet;

--
-- TOC entry 3498 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE game; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON TABLE public.game IS 'Игровые сессии';


--
-- TOC entry 3499 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN game.id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.game.id IS 'Уникальный идентификатор игры';


--
-- TOC entry 3500 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN game.quizz_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.game.quizz_id IS 'ID квиза, используемого в игре';


--
-- TOC entry 3501 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN game.leader_user_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.game.leader_user_id IS 'ID пользователя-лидера (создателя) игры';


--
-- TOC entry 3502 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN game.link_key; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.game.link_key IS 'Уникальный ключ для подключения к игре';


--
-- TOC entry 3503 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN game.create_at; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.game.create_at IS 'Время создания игры';


--
-- TOC entry 3504 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN game.quizz_state; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.game.quizz_state IS 'Состояние игры (Registry, Active, Finished и т.д.)';


--
-- TOC entry 3505 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN game.questions_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.game.questions_id IS 'Массив ID вопросов, используемых в игре (порядок)';


--
-- TOC entry 222 (class 1259 OID 16429)
-- Name: game_id_seq; Type: SEQUENCE; Schema: public; Owner: quizznet
--

ALTER TABLE public.game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16416)
-- Name: question; Type: TABLE; Schema: public; Owner: quizznet
--

CREATE TABLE public.question (
    id bigint NOT NULL,
    quizz_id bigint NOT NULL,
    question_data text NOT NULL,
    answer_data text NOT NULL,
    answer_type text NOT NULL,
    question_type text NOT NULL,
    correct_answer text NOT NULL,
    points bigint DEFAULT 1 NOT NULL,
    "order" integer NOT NULL
);


ALTER TABLE public.question OWNER TO quizznet;

--
-- TOC entry 3506 (class 0 OID 0)
-- Dependencies: 221
-- Name: TABLE question; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON TABLE public.question IS 'Вопросы квизов';


--
-- TOC entry 3507 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question.id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question.id IS 'Уникальный идентификатор вопроса';


--
-- TOC entry 3508 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question.quizz_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question.quizz_id IS 'ID квиза, к которому относится вопрос';


--
-- TOC entry 3509 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question.question_data; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question.question_data IS 'Текст вопроса';


--
-- TOC entry 3510 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question.answer_data; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question.answer_data IS 'Данные для ответа (варианты и т.д.)';


--
-- TOC entry 3511 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question.answer_type; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question.answer_type IS 'Тип ответа (одиночный, множественный и т.д.)';


--
-- TOC entry 3512 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question.question_type; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question.question_type IS 'Тип вопроса';


--
-- TOC entry 3513 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question.correct_answer; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question.correct_answer IS 'Правильный ответ';


--
-- TOC entry 3514 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question.points; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question.points IS 'Количество баллов за правильный ответ';


--
-- TOC entry 3515 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN question."order"; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.question."order" IS 'Порядковый номер вопроса в квизе';


--
-- TOC entry 220 (class 1259 OID 16415)
-- Name: question_id_seq; Type: SEQUENCE; Schema: public; Owner: quizznet
--

ALTER TABLE public.question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16408)
-- Name: quizz; Type: TABLE; Schema: public; Owner: quizznet
--

CREATE TABLE public.quizz (
    id bigint NOT NULL,
    name text NOT NULL,
    description text
);


ALTER TABLE public.quizz OWNER TO quizznet;

--
-- TOC entry 3516 (class 0 OID 0)
-- Dependencies: 219
-- Name: TABLE quizz; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON TABLE public.quizz IS 'Опросы / квизы';


--
-- TOC entry 3517 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN quizz.id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.quizz.id IS 'Уникальный идентификатор';


--
-- TOC entry 3518 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN quizz.name; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.quizz.name IS 'Название квиза';


--
-- TOC entry 3519 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN quizz.description; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.quizz.description IS 'Описание квиза';


--
-- TOC entry 218 (class 1259 OID 16407)
-- Name: quizz_id_seq; Type: SEQUENCE; Schema: public; Owner: quizznet
--

ALTER TABLE public.quizz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16452)
-- Name: user_answers; Type: TABLE; Schema: public; Owner: quizznet
--

CREATE TABLE public.user_answers (
    id bigint NOT NULL,
    game_id bigint NOT NULL,
    user_id bigint NOT NULL,
    question_id bigint NOT NULL,
    answer text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.user_answers OWNER TO quizznet;

--
-- TOC entry 3520 (class 0 OID 0)
-- Dependencies: 225
-- Name: TABLE user_answers; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON TABLE public.user_answers IS 'Ответы пользователей на вопросы в рамках игры';


--
-- TOC entry 3521 (class 0 OID 0)
-- Dependencies: 225
-- Name: COLUMN user_answers.id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.user_answers.id IS 'Уникальный идентификатор ответа';


--
-- TOC entry 3522 (class 0 OID 0)
-- Dependencies: 225
-- Name: COLUMN user_answers.game_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.user_answers.game_id IS 'ID игры';


--
-- TOC entry 3523 (class 0 OID 0)
-- Dependencies: 225
-- Name: COLUMN user_answers.user_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.user_answers.user_id IS 'ID пользователя';


--
-- TOC entry 3524 (class 0 OID 0)
-- Dependencies: 225
-- Name: COLUMN user_answers.question_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.user_answers.question_id IS 'ID вопроса';


--
-- TOC entry 3525 (class 0 OID 0)
-- Dependencies: 225
-- Name: COLUMN user_answers.answer; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.user_answers.answer IS 'Ответ пользователя';


--
-- TOC entry 224 (class 1259 OID 16451)
-- Name: user_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: quizznet
--

ALTER TABLE public.user_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16397)
-- Name: users; Type: TABLE; Schema: public; Owner: quizznet
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    nickname text NOT NULL,
    password text DEFAULT ''::text NOT NULL,
    user_type text DEFAULT 'User'::text NOT NULL,
    last_auth timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO quizznet;

--
-- TOC entry 3526 (class 0 OID 0)
-- Dependencies: 217
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON TABLE public.users IS 'Пользователи';


--
-- TOC entry 3527 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN users.id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users.id IS 'Уникальный идентификатор (автоинкремент)';


--
-- TOC entry 3528 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN users.nickname; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users.nickname IS 'Никнейм пользователя';


--
-- TOC entry 3529 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN users.password; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users.password IS 'Хеш пароля';


--
-- TOC entry 3530 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN users.user_type; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users.user_type IS 'Тип пользователя (User, Admin и т.д.)';


--
-- TOC entry 3531 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN users.last_auth; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users.last_auth IS 'Время последней авторизации';


--
-- TOC entry 227 (class 1259 OID 16476)
-- Name: users_game; Type: TABLE; Schema: public; Owner: quizznet
--

CREATE TABLE public.users_game (
    id bigint NOT NULL,
    game_id bigint NOT NULL,
    user_id bigint NOT NULL,
    score bigint NOT NULL
);


ALTER TABLE public.users_game OWNER TO quizznet;

--
-- TOC entry 3532 (class 0 OID 0)
-- Dependencies: 227
-- Name: TABLE users_game; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON TABLE public.users_game IS 'Участники игр и их результаты';


--
-- TOC entry 3533 (class 0 OID 0)
-- Dependencies: 227
-- Name: COLUMN users_game.id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users_game.id IS 'Уникальный идентификатор записи';


--
-- TOC entry 3534 (class 0 OID 0)
-- Dependencies: 227
-- Name: COLUMN users_game.game_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users_game.game_id IS 'ID игры';


--
-- TOC entry 3535 (class 0 OID 0)
-- Dependencies: 227
-- Name: COLUMN users_game.user_id; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users_game.user_id IS 'ID пользователя';


--
-- TOC entry 3536 (class 0 OID 0)
-- Dependencies: 227
-- Name: COLUMN users_game.score; Type: COMMENT; Schema: public; Owner: quizznet
--

COMMENT ON COLUMN public.users_game.score IS 'Набранное количество очков';


--
-- TOC entry 226 (class 1259 OID 16475)
-- Name: users_game_id_seq; Type: SEQUENCE; Schema: public; Owner: quizznet
--

ALTER TABLE public.users_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16396)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: quizznet
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3487 (class 0 OID 16430)
-- Dependencies: 223
-- Data for Name: game; Type: TABLE DATA; Schema: public; Owner: quizznet
--

INSERT INTO public.game VALUES (1, 1, 1, '75a76d3b-8054-4a90-85bc-d346bc2486db', '2026-05-20 12:00:39.858714', 'Registry', '{1,2,15,16,17,3,4,5,6,7,8,9,10,11,12,13,14,18,19,20,21,22,23,24,25}');


--
-- TOC entry 3485 (class 0 OID 16416)
-- Dependencies: 221
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: quizznet
--

INSERT INTO public.question VALUES (15, 1, '{"text":"Эта конструкция из стальных колец или китового уса, надеваемая под юбку, была популярна в середине XIX века."}', '{"options":["- A) Турнюр","- B) Кринолин","- C) Панье","- D) Фижмы"]}', 'Select', 'Text', '- B) Кринолин', 1, 0);
INSERT INTO public.question VALUES (16, 1, '{"text":"Это самый простой и базовый узор в вязании спицами, при котором все ряды (и лицевые, и изнаночные) провязываются только лицевыми петлями."}', '{"options":["- A) Чулочная вязка","- B) Жемчужный узор","- C) Резинка","- D) Платочная вязка"]}', 'Select', 'Text', '- D) Платочная вязка', 1, 0);
INSERT INTO public.question VALUES (17, 1, '{"text":"Этот объёмный элемент вязания напоминает зёрнышко воздушной кукурузы."}', '{"options":["- A) Ажур","- B) Попкорн","- C) Коса","- D) Ромб"]}', 'Select', 'Text', '- B) Попкорн', 1, 0);
INSERT INTO public.question VALUES (2, 1, '{"text":"Уменьшение количества рабочих петель в вязаном полотне называется?"}', '{"options":["- A) Кромочная","- B) Накид","- C) Реглан","- D) Убавка"]}', 'Select', 'Text', '- D) Убавка', 1, 0);
INSERT INTO public.question VALUES (1, 1, '{"text":"Что служит основой (началом) при вязании крючком?"}', '{"options":["- A) Наборный край","- B) Воздушная петля","- C) Кольцо Амигуруми"]}', 'Select', 'Text', '- C) Кольцо Амигуруми', 1, 0);
INSERT INTO public.question VALUES (3, 1, '{"text":"Этот способ вязания спицами, позволяет создать бесшовное полотно в форме трубы."}', '{"options":["- A) Продольное вязание","- B) Поперечное вязание","- C) Круговое вязание","- D) Филейное вязание"]}', 'Select', 'Text', '- C) Круговое вязание', 1, 0);
INSERT INTO public.question VALUES (4, 1, '{"text":"В японском вязании этот термин обозначает искусство вязания маленьких игрушек — обычно крючком, но иногда и спицами."}', '{"options":["- A) Оригами","- B) Амигуруми","- C) Темари","- D) Сашико"]}', 'Select', 'Text', '- B) Амигуруми', 1, 0);
INSERT INTO public.question VALUES (5, 1, '{"url":"http://localhost:3001/api/images/95758d9e-e554-4174-a99c-a9824d85c75b.jpeg"}', '{"options":["- A) Кольцо","- B) Напёрсток","- C) Катушка","- D) Булавка"]}', 'Select', 'Image', '- B) Напёрсток', 1, 0);
INSERT INTO public.question VALUES (6, 1, '{"text":"Этот портновский инструмент, похожий на колёсико с ручкой, оставляет след на ткани и помогает перенести линии выкройки. Часто его называют «копиркой»."}', '{"options":["- A) Мел","- B) Копировальный ролик","- C) Линейка","- D) Шило "]}', 'Select', 'Text', '- B) Копировальный ролик', 1, 0);
INSERT INTO public.question VALUES (7, 1, '{"url":"http://localhost:3001/api/images/2e2c22e6-4dc6-4c51-8d53-df5d0d43406e.jpeg"}', '{"options":["- A) Портновские ножницы","- B) Ножницы зигзаг","- C) Маникюрные ножницы","- D) Садовые ножницы"]}', 'Select', 'Image', '- B) Ножницы зигзаг', 1, 0);
INSERT INTO public.question VALUES (8, 1, '{"text":"Этот маленький инструмент с острым лезвием и шариком-предохранителем на конце помогает быстро и аккуратно \"раскрыть\" шов."}', '{"options":["- A) Нож","- B) Скальпель","- C) Распарыватель","- D) Ножницы"]}', 'Select', 'Text', '- C) Распарыватель', 1, 0);
INSERT INTO public.question VALUES (9, 1, '{"text":"Это натуральное волокно получают от пушистого зверька из семейства верблюдовых, обитающего в Андах. Пряжа из него очень тёплая и мягкая."}', '{"options":["- A) Мохер","- B) Альпака","- C) Ангора","- D) Кашемир"]}', 'Select', 'Text', '- B) Альпака', 1, 0);
INSERT INTO public.question VALUES (10, 1, '{"text":"Название этой породы тонкорунных овец, дающих особенно мягкую шерсть, происходит от породы, выведенной в Испании."}', '{"options":["- A) Шетланд","- B) Корридейл","- C) Меринос","- D) Линкольн"]}', 'Select', 'Text', '- C) Меринос', 1, 0);
INSERT INTO public.question VALUES (11, 1, '{"text":"Этот параметр пряжи показывает длину нити в метрах на один грамм, иначе называется линейной плотностью."}', '{"options":["- A) Толщина","- B) Вес","- C) Метрический номер","- D) Крутка"]}', 'Select', 'Text', '- C) Метрический номер', 1, 0);
INSERT INTO public.question VALUES (12, 1, '{"text":"Эта пряжа окрашена не полностью, а отдельными участками, что при вязании создаёт узор из цветных полос."}', '{"options":["- A) Меланжевая пряжа","- B) Секционная пряжа","- C) Однотонная пряжа","- D) Градиентная пряжа"]}', 'Select', 'Text', '- B) Секционная пряжа', 1, 0);
INSERT INTO public.question VALUES (13, 1, '{"text":"Эта заботливая волшебница из «Гарри Поттера» каждый год вяжет свитера для всех своих детей и даже для Гарри."}', '{"options":["- A) Минерва Макгонагалл","- B) Беллатриса Лестрейндж","- C) Молли Уизли","- D) Нарцисса Малфой "]}', 'Select', 'Text', '- C) Молли Уизли', 1, 0);
INSERT INTO public.question VALUES (14, 1, '{"url":"http://localhost:3001/api/images/b812b2df-a5d8-42d2-a2eb-804ef4a51532.jpeg"}', '{"options":["- A) Касабланка","- B) Унесённые ветром","- C) Римские каникулы","- D) Завтрак у Тиффани "]}', 'Select', 'Image', '- B) Унесённые ветром', 1, 0);
INSERT INTO public.question VALUES (18, 1, '{"text":"Этот традиционный ирландский узор спицами представляет собой переплетение жгутов на фоне изнаночной глади."}', '{"options":["- A) Фэр-айл","- B) Аранское вязание","- C) Интарсия","- D) Бриошь"]}', 'Select', 'Text', '- B) Аранское вязание', 1, 0);
INSERT INTO public.question VALUES (19, 1, '{"text":"Этот свитер с геометрическим жаккардовым узором, созданный в 1950-х годах, назван в честь знаменитого норвежского лыжника."}', '{"options":["- A) Лусенкофте","- B) Свитер Мариуса","- C) Исландский лопапейса","- D) Селбу-розе"]}', 'Select', 'Text', '- B) Свитер Мариуса', 1, 0);
INSERT INTO public.question VALUES (20, 1, '{"url":"http://localhost:3001/api/images/5abdb1fc-1970-4401-8c3b-f48c3756e10c.jpeg"}', '{"options":["- A) Ришелье","- B) Мережка","- C) Хардангер","- D) Крестик"]}', 'Select', 'Image', '- C) Хардангер', 1, 0);
INSERT INTO public.question VALUES (21, 1, '{"text":"Этот пуховый платок из козьего пуха, связанный на спицах, стал символом целого края. Говорят, его можно продеть сквозь обручальное кольцо."}', '{"options":["- A) Павловопосадский платок","- B) Оренбургский пуховый платок","- C) Вологодский платок","- D) Елецкий платок"]}', 'Select', 'Text', '- B) Оренбургский пуховый платок', 1, 0);
INSERT INTO public.question VALUES (22, 1, '{"text":"Этот инструмент для прядения, воспетый в народных песнях и сказках, состоит из лопасти для кудели и сиденья-донца."}', '{"options":["- A) Веретено","- B) Прялка","- C) Ткацкий станок","- D) Чесалка"]}', 'Select', 'Text', '- B) Прялка', 1, 0);
INSERT INTO public.question VALUES (23, 1, '{"text":"Это синтетическое волокно, получаемое из угля, нефти и воздуха, используется для парашютов и колготок."}', '{"options":["- A) Хлопок","- B) Капрон","- C) Вискоза","- D) Лён"]}', 'Select', 'Text', '- B) Капрон', 1, 0);
INSERT INTO public.question VALUES (24, 1, '{"text":"Как называется свойство ткани линять при трении, отдавать краску на другие поверхности?"}', '{"options":["- A) Выцветание","- B) Усадка","- C) Маркость","- D) Пилингуемость"]}', 'Select', 'Text', '- C) Маркость', 1, 0);
INSERT INTO public.question VALUES (25, 1, '{"url":"http://localhost:3001/api/images/1d6f0fde-1ec5-49cc-aa8c-b15083b830f8.jpeg"}', '{"options":["- A) Вязаное граффити","- B) Граффити","- C) Мурал","- D) Инсталляция"]}', 'Select', 'Image', '- A) Вязаное граффити', 1, 0);


--
-- TOC entry 3483 (class 0 OID 16408)
-- Dependencies: 219
-- Data for Name: quizz; Type: TABLE DATA; Schema: public; Owner: quizznet
--

INSERT INTO public.quizz VALUES (1, 'Вязальный квиз!', '@pekki_knit ');


--
-- TOC entry 3489 (class 0 OID 16452)
-- Dependencies: 225
-- Data for Name: user_answers; Type: TABLE DATA; Schema: public; Owner: quizznet
--



--
-- TOC entry 3481 (class 0 OID 16397)
-- Dependencies: 217
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: quizznet
--

INSERT INTO public.users VALUES (1, 'veronika', 'heZRgcplh+Qe2Iaywxj5ug==', 'Admin', '2026-05-20 11:41:55.978021');


--
-- TOC entry 3491 (class 0 OID 16476)
-- Dependencies: 227
-- Data for Name: users_game; Type: TABLE DATA; Schema: public; Owner: quizznet
--



--
-- TOC entry 3537 (class 0 OID 0)
-- Dependencies: 222
-- Name: game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quizznet
--

SELECT pg_catalog.setval('public.game_id_seq', 1, true);


--
-- TOC entry 3538 (class 0 OID 0)
-- Dependencies: 220
-- Name: question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quizznet
--

SELECT pg_catalog.setval('public.question_id_seq', 25, true);


--
-- TOC entry 3539 (class 0 OID 0)
-- Dependencies: 218
-- Name: quizz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quizznet
--

SELECT pg_catalog.setval('public.quizz_id_seq', 1, true);


--
-- TOC entry 3540 (class 0 OID 0)
-- Dependencies: 224
-- Name: user_answers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quizznet
--

SELECT pg_catalog.setval('public.user_answers_id_seq', 1, false);


--
-- TOC entry 3541 (class 0 OID 0)
-- Dependencies: 226
-- Name: users_game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quizznet
--

SELECT pg_catalog.setval('public.users_game_id_seq', 1, false);


--
-- TOC entry 3542 (class 0 OID 0)
-- Dependencies: 216
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quizznet
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- TOC entry 3317 (class 2606 OID 16440)
-- Name: game game_logic_pk; Type: CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_logic_pk PRIMARY KEY (id);


--
-- TOC entry 3315 (class 2606 OID 16423)
-- Name: question question_pk; Type: CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pk PRIMARY KEY (id);


--
-- TOC entry 3312 (class 2606 OID 16414)
-- Name: quizz survey_pk; Type: CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.quizz
    ADD CONSTRAINT survey_pk PRIMARY KEY (id);


--
-- TOC entry 3324 (class 2606 OID 16459)
-- Name: user_answers user_answers_pk; Type: CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_pk PRIMARY KEY (id);


--
-- TOC entry 3328 (class 2606 OID 16480)
-- Name: users_game users_game_pk; Type: CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.users_game
    ADD CONSTRAINT users_game_pk PRIMARY KEY (id);


--
-- TOC entry 3310 (class 2606 OID 16406)
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- TOC entry 3318 (class 1259 OID 16492)
-- Name: idx_game_leader_user_id; Type: INDEX; Schema: public; Owner: quizznet
--

CREATE INDEX idx_game_leader_user_id ON public.game USING btree (leader_user_id);


--
-- TOC entry 3319 (class 1259 OID 16491)
-- Name: idx_game_quizz_id; Type: INDEX; Schema: public; Owner: quizznet
--

CREATE INDEX idx_game_quizz_id ON public.game USING btree (quizz_id);


--
-- TOC entry 3313 (class 1259 OID 16493)
-- Name: idx_question_quizz_id; Type: INDEX; Schema: public; Owner: quizznet
--

CREATE INDEX idx_question_quizz_id ON public.question USING btree (quizz_id);


--
-- TOC entry 3320 (class 1259 OID 16494)
-- Name: idx_user_answers_game_id; Type: INDEX; Schema: public; Owner: quizznet
--

CREATE INDEX idx_user_answers_game_id ON public.user_answers USING btree (game_id);


--
-- TOC entry 3321 (class 1259 OID 16496)
-- Name: idx_user_answers_question_id; Type: INDEX; Schema: public; Owner: quizznet
--

CREATE INDEX idx_user_answers_question_id ON public.user_answers USING btree (question_id);


--
-- TOC entry 3322 (class 1259 OID 16495)
-- Name: idx_user_answers_user_id; Type: INDEX; Schema: public; Owner: quizznet
--

CREATE INDEX idx_user_answers_user_id ON public.user_answers USING btree (user_id);


--
-- TOC entry 3325 (class 1259 OID 16497)
-- Name: idx_users_game_game_id; Type: INDEX; Schema: public; Owner: quizznet
--

CREATE INDEX idx_users_game_game_id ON public.users_game USING btree (game_id);


--
-- TOC entry 3326 (class 1259 OID 16498)
-- Name: idx_users_game_user_id; Type: INDEX; Schema: public; Owner: quizznet
--

CREATE INDEX idx_users_game_user_id ON public.users_game USING btree (user_id);


--
-- TOC entry 3330 (class 2606 OID 16446)
-- Name: game game_quizz_fk; Type: FK CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_quizz_fk FOREIGN KEY (quizz_id) REFERENCES public.quizz(id);


--
-- TOC entry 3331 (class 2606 OID 16441)
-- Name: game game_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_users_fk FOREIGN KEY (leader_user_id) REFERENCES public.users(id);


--
-- TOC entry 3329 (class 2606 OID 16424)
-- Name: question question_quizz_fk; Type: FK CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_quizz_fk FOREIGN KEY (quizz_id) REFERENCES public.quizz(id);


--
-- TOC entry 3332 (class 2606 OID 16460)
-- Name: user_answers user_answers_game_fk; Type: FK CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_game_fk FOREIGN KEY (game_id) REFERENCES public.game(id);


--
-- TOC entry 3333 (class 2606 OID 16470)
-- Name: user_answers user_answers_question_fk; Type: FK CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_question_fk FOREIGN KEY (question_id) REFERENCES public.question(id);


--
-- TOC entry 3334 (class 2606 OID 16465)
-- Name: user_answers user_answers_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3335 (class 2606 OID 16481)
-- Name: users_game users_game_game_fk; Type: FK CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.users_game
    ADD CONSTRAINT users_game_game_fk FOREIGN KEY (game_id) REFERENCES public.game(id);


--
-- TOC entry 3336 (class 2606 OID 16486)
-- Name: users_game users_game_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: quizznet
--

ALTER TABLE ONLY public.users_game
    ADD CONSTRAINT users_game_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id);

